server:
  port: 8081

operator:
  userId: 30000141

retrofit:
  connection:
    readTimeout: 20000
    writeTimeout: 10000
    connectTimeout: 5000
    maxIdleConnections: 5 # The maximum number of idle connections for each address.
    keepAliveDuration: 5 # The time (minutes) to live for each idle connections.
    retryTimes: 0

  # identity: current available
  # baseUrl: the base part of business system url, would be changed by nginx location, "/" is not required to be the end of url
  endpoints:
  - identity: crm-classcenter
    baseUrl: https://crm.pipacoding.com/
  - identity: crm-audit
    baseUrl: http://10.122.170.101:80/
  - identity: order-center
    baseUrl: https://crm.pipacoding.com/

  log:
    enabled: true
    content: BASIC # NONE, BASIC, HEADERS, BODY
    level: INFO

